use_frameworks!

target 'MinterMy_Example' do
  pod 'MinterMy', :path => '../'

  target 'MinterMy_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0.2'
  end
end
