source 'https://github.com/Cocoapods/Specs'

use_frameworks!

target 'MinterMy_Example' do
  pod 'MinterMy'
	pod 'MinterCore'

  target 'MinterMy_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0.2'
  end
end
